### ISSUE TITLE
Proposed Section: How to Apply

### ISSUE THREAD

**Issue by ktsubouchi** [elevation-energy/public-posts#2]
Hi Justin, 

I think it would be beneficial to interested candidates to have a section with instructions on how to apply. :)

**Comment by jtallant** [comment]
Haha, yes thanks! Last time we used LaraJobs people were able to reply directly to the listing and send an E-mail. Apparently things have changed! I updated the markdown file but resumes can be sent to tech@elevationeg.com

**Comment by ktsubouchi** [comment]
That's what I thought too but when the link is clicked on LaraJobs, it goes directly to this repo.  Anyway, thanks!
